---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)

library(tibble)
library(crayon)

## from: https://github.com/r-lib/crayon/issues/96
# options(crayon.enabled = NULL)
```

# rendertest

Trying to figure out encoding problems when I use github actions to render readme and pkgdown websites.

```{r}
.Platform
```

```{r}
crayon::has_color()
```

```{r}
er <- errorCondition(
  message = paste("crayon::has_color() ?:",
                  crayon::has_color(),
                  "\nresult:",
                  crayon::red("A barfoo error")))
er
```


## Example

Print a tibble:

```{r cars}
as_tibble(cars)
```

## unicode
Print some unicode:
Plain old unicode seems to work.

Ā  ā Ġ ☂


## Example Crayon

print using crayon directly

```{r}
cat(blue("Hello", "world!\n"))
```


## Set options

```{r}
## from: https://github.com/r-lib/crayon/issues/96
options(crayon.enabled = NULL)

cat(blue("Hello", "world!\n"))

as_tibble(cars)


```


reset option

```{r}

options(crayon.enabled = TRUE)

cat(blue("Hello", "world!\n"))

as_tibble(cars)


```


Try `fansi`

```{r}
old.hooks <- fansi::set_knit_hooks(knitr::knit_hooks)
```


check output

```{r}

cat(blue("Hello", "world!\n"))

as_tibble(cars)

er

```


## session

```{r sessioninfo}
sessioninfo::session_info()
```

