on:
  push:
     branches:
       - master


name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown","tibble","sessioninfo","crayon","fansi"))'
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'

      - name: Deploy to GitHub Pages
        run: |
          cd _book
          git init
          git config user.name "Michael Schramm"
          git config user.email ${{ secrets.EMAIL }}
          git config --global push.default simple
          git add .
          git status
          git commit -m 'update book'
          git push https://${{github.actor}}:${{ secrets.GH_PAT }}@github.com/${{github.repository}}.git HEAD:gh-pages --force

